<?php include ("../cat2_shortcuts.php");
echo '<br>'.PHP_EOL;
echo $button_1.'mose_1\')">1. Mose</button>'.PHP_EOL;
echo $div_book.'mose_1">'.PHP_EOL;
echo '1. Mose 3:15:<br>'.PHP_EOL;
echo $gold_1.'Und ich werde Feindschaft setzen zwischen dir und der Frau, zwischen deinem Samen und ihrem Samen; er wird dir den Kopf zertreten, und du wirst ihn in die Ferse stechen.<br>'.$gold_2.PHP_EOL;
echo 'Diese erste Prophetie über den „Samen der Frau“ wird oft als Ankündigung von Jesus gedeutet. Er würde den Teufel (Schlange) besiegen, aber dabei selbst leiden (z. B. durch die Kreuzigung).<br>'.PHP_EOL;
echo '-----------<br>'.PHP_EOL;
echo '1. Mose 22, Verse 1-2:<br>'.PHP_EOL;
echo $gold_1.'Einige Zeit später stellte Gott Abraham auf die Probe. Er sagte zu ihm: »Abraham!« Der antwortete: »Hier bin ich!« 
Gott sagte: »Nimm deinen einzigen, deinen geliebten Sohn Isaak, und geh mit ihm in das Land Morija. Bring ihn dort als Brandopfer dar – auf einem Berg, den ich dir nennen werde.<br>'.$gold_2.PHP_EOL;
echo 'Das Gebiet Morija ist später das Land um Jerusalem und der Berg den Gott ihm zeigte hieß schon damals "Golgotha" was "Ort des Schädels" heißt.<br>'.PHP_EOL;
echo '-----------<br>'.PHP_EOL;
echo '1. Mose, 37-50:<br>'.PHP_EOL;
echo 'Josef, einer der Söhne Jakobs, wird in vielerlei Hinsicht als prophetisches Bild für Jesus gesehen:<br>'.PHP_EOL;
echo 'Josef wurde von seinen Brüdern abgelehnt und verkauft → Jesus wurde von seinem Volk abgelehnt und verraten.<br>'.PHP_EOL;
echo 'Josef wurde für Silber verkauft (20 Silberstücke) → Jesus für 30 Silberstücke.<br>'.PHP_EOL;
echo 'Josef wurde ins Gefängnis geworfen, bevor er erhöht wurde → Jesus starb und wurde danach verherrlicht.<br>'.PHP_EOL;
echo 'Josef rettete seine Brüder und die Welt vor einer Hungersnot → Jesus rettet die Welt vor geistlichem Tod.<br>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo $button_1.'mose_2\')">2. Mose</button>'.PHP_EOL;
echo $div_book.'mose_2"'.PHP_EOL;
echo 'Test'.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo ''.PHP_EOL;
echo '</div>'.PHP_EOL;
?>