<p><a href="">Wolfgang Schäuble</a><a href="https://de.wikipedia.org/wiki/Wolfgang_Sch%C3%A4uble"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Angela Merkel</a><a href="https://de.wikipedia.org/wiki/Angela_Merkel"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Ralph Brinkhaus</a><a href="https://de.wikipedia.org/wiki/Ralph_Brinkhaus"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Daniel Caspary</a><a href="https://de.wikipedia.org/wiki/Daniel_Caspary"><font color="black"> - Wikipedia</font></a><br /></p>
				    <p><a href="A-Laschet">Armin Laschet</a><a href="https://de.wikipedia.org/wiki/Armin_Laschet"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Paul Ziemiak</a><a href="https://de.wikipedia.org/wiki/Paul_Ziemiak"><font color="black"> - Wikipedia</font></a><br /></p>
				    <p><a href="">Volker Bouffier</a><a href="https://de.wikipedia.org/wiki/Volker_Bouffier"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Silvia Breher</a><a href="https://de.wikipedia.org/wiki/Silvia_Breher"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Julia Klöckner</a><a href="https://de.wikipedia.org/wiki/Julia_Kl%C3%B6ckner"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Jens Spahn</a><a href="https://de.wikipedia.org/wiki/Jens_Spahn"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Thomas Strobl</a><a href="https://de.wikipedia.org/wiki/Thomas_Strobl"><font color="black"> - Wikipedia</font></a><br /></p>
				    <p><a href="">Philipp Murmann</a><a href="https://de.wikipedia.org/wiki/Philipp_Murmann"><font color="black"> - Wikipedia</font></a><br /></p>
				    <p><a href="">Bernd Althusmann</a><a href="https://de.wikipedia.org/wiki/Bernd_Althusmann"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Monika Grütters</a><a href="https://de.wikipedia.org/wiki/Monika_Gr%C3%BCtters"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Reiner Haseloff</a><a href="https://de.wikipedia.org/wiki/Reiner_Haseloff"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Michael Kretschmer</a><a href="https://de.wikipedia.org/wiki/Michael_Kretschmer"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Karl-Josef Laumann</a><a href="https://de.wikipedia.org/wiki/Karl-Josef_Laumann"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Norbert Röttgen</a><a href="https://de.wikipedia.org/wiki/Norbert_R%C3%B6ttgen"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Annette Widmann-Mauz</a><a href="https://de.wikipedia.org/wiki/Annette_Widmann-Mauz"><font color="black"> - Wikipedia</font></a><br /></p>
				    <p><a href="">Daniel Günther</a><a href="https://de.wikipedia.org/wiki/Daniel_G%C3%BCnther"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Tobias Hans</a><a href="https://de.wikipedia.org/wiki/Tobias_Hans"><font color="black"> - Wikipedia</font></a><br />
				    <a href="">Stefan Hennewig</a><a href="https://de.wikipedia.org/wiki/Stefan_Hennewig"><font color="black"> - Wikipedia</font></a></p>
