<select name="nightcore">
                    <option value="" disabled selected></option>
                <option value="nightcore">Airplanes</option>
                <option value="nightcore">All the right Moves</option>
                <option value="nightcore">Angel of Darkness</option>
                <option value="nightcore">Angel with a Shotgun</option>
                <option value="nightcore">Anima Libera</option>
                <option value="nightcore">Atemlos</option>
                <option value="nightcore">Au Revoir</option>
                <option value="nightcore">Battlefield</option>
                <option value="nightcore">Breaking the Habit</option>
                <option value="nightcore">Calling all the Monsters</option>
                <option value="nightcore">Colors of the Rainbow</option>
                <option value="nightcore">Comatose</option>
                <option value="nightcore">Dam Dadi Doo</option>
                <option value="nightcore">Disturbia</option>
                <option value="nightcore">DotA</option>
                <option value="nightcore">Dragostea Din Tei</option>
                <option value="nightcore">Echt</option>
                <option value="nightcore">Fireflies</option>
                <option value="nightcore">Flute</option>
                <option value="nightcore">Glad you Came</option>
                <option value="nightcore">Hurry up and save me</option>
                <option value="nightcore">Ich bin Ich</option>
                <option value="nightcore">I Cry</option>
                <option value="nightcore">Infinity</option>
                <option value="nightcore">I'm Blue</option>
                <option value="nightcore">Last Resort</option>
                <option value="nightcore">Lieder</option>
                <option value="nightcore">Monster (Skillet)</option>
                <option value="nightcore">Moonlight Shadow</option>
                <option value="nightcore">Miracle</option>
                <option value="nightcore">Perfect Melodie</option>
                <option value="nightcore">Pirates of the Caribbean</option>
                <option value="nightcore">Rather Be</option>
                <option value="nightcore">Raver's Fantasy</option>
                <option value="nightcore">Raver's in the UK</option>
                <option value="nightcore">RiP</option>
                <option value="nightcore">RiP (Rita Ora)</option>
                <option value="nightcore">Stamp on the Ground</option>
                <option value="nightcore">Tacata</option>
                <option value="nightcore">Tetris</option>
                <option value="nightcore">The Black Pearl</option>
                <option value="nightcore">When the Beat drops out</option>
                <option value="nightcore">When you Leave</option>
                <option value="nightcore">Whispers in the Dark</option>
		        </select>